[[Playlists]]
name = "Discover Weekly"
id = "37i9dQZEVXcPuW1vx9zAVv"

[[Playlists]]
name = "Release Radar"
id = "37i9dQZEVXbh5TvCuo3k55"

[[Playlists]]
name = "Daily Mix 1"
id = "37i9dQZF1E39y6Hg6uOQnN"

[[Playlists]]
name = "Daily Mix 2"
id = "37i9dQZF1E35RKcREopRvk"

[[Playlists]]
name = "Daily Mix 3"
id = "37i9dQZF1E38AHNgmFwNTa"

[[Playlists]]
name = "Daily Mix 4"
id = "37i9dQZF1E37o37HP5F3Pf"

[[Playlists]]
name = "Daily Mix 5"
id = "37i9dQZF1E375e4Inyj09V"

[[Playlists]]
name = "Daily Mix 6"
id = "37i9dQZF1E35QdGpYmc8Hi"
